name: 构建

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - uses: actions/checkout@v4
      
      # 设置JDK环境
      - name: 安装JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
          
      # 执行Gradle构建
      - name: 使用Gradle构建
        run: ./gradlew build
        
      # 上传构建产物（可下载）
      - name: 上传构建结果
        uses: actions/upload-artifact@v4
        with:
           name: build-output
           path: |
            build/libs/*.jar
            build/reports/**
           if-no-files-found: error
